development:
  password: your API key
  theme_id: "theme ID"
  store: store.myshopify.com
  ignore_files:
    - config/settings_data.json
    - assets/gift-card.scss
    - assets/theme.scss
    - assets/ico-select.svg